#!/usr/bin/env sh
echo $1
echo "${2}"

if [ $1 == "save" ]
then
    echo "Saving commit message!"
    cp "${2}" "$(git rev-parse --git-path pre-commit-saved-commit-msg)"
else
    set -e
    set -u

    msg_file=$(git rev-parse --git-path pre-commit-saved-commit-msg)
    [ -r "${msg_file}" ] || exit 0

    nr_of_non_empty_lines=$(sed -e '/^#/d' -e '/^[[:space:]]*$/d' "${1}" | wc -l)
    if [ "${nr_of_non_empty_lines}" -ne 0 ]
    then
        echo "# last commit message:" >> "${1}"
        sed -e '/^#/d' -e 's/^/# /' "${msg_file}" >> "${1}"
        exit 0
    fi

    echo 'restoring commit message...'
    cp "${msg_file}" "${2}"
fi
