#!/usr/bin/env python3
import os
import shutil
import sys

OLD_MSG = '.git/pre-commit-saved-commit-msg'

def main():
    os.system(f"cat {sys.argv[1]}")
    if os.path.isfile(OLD_MSG):
        with open(OLD_MSG,"r") as of:
            old_msg = of.read()
            with open(sys.argv[1],"r+") as f:
                orig = f.read()
                f.seek(0)
                f.write(old_msg)
                f.write(orig)

if __name__ == '__main__':
    exit(main())
