#!/usr/bin/env python3
import shutil
import sys


def main():
    lines = []
    with open(sys.argv[1]) as f:
        for line in f:
            if line.startswith("#"):
                continue
            if not line.strip():
                continue
            lines.append(f"# {line}")
    if lines:
        lines.insert(0,"\n") # Add a new line at the beginning of the commit message
        lines.insert(1,"# Previous Commit Message:\n")
        if len(lines) > 3:
            lines.insert(3,"\n") # add a new line after the title
        with open('.git/pre-commit-saved-commit-msg','w') as f:
            f.writelines(lines)

if __name__ == '__main__':
    exit(main())
