#!/usr/bin/env python3
import shutil
import sys


def main():
    lines = []
    with open(sys.argv[1]) as f:
        for line in f:
            if line.startswith("#"):
                continue
            if not line.strip():
                continue
            lines.append(f"# {line}")
    if lines:
        lines.insert(1,"\n")
        with open('.git/pre-commit-saved-commit-msg','w') as f:
            f.write("# Previous Commit Message:\n")
            f.writelines(lines)

if __name__ == '__main__':
    exit(main())
